### PR TITLE
Handle tar filemodes that overllap with 0120000

### LINKED ISSUE #49: tar2rpm: rpm -ivh of generated .rpm fails with cpio: Digest mismatch
I have generated a valid, functioning TAR file with Apache Ant (file says: POSIX tar archive). 
When I create an RPM file with tar2rpm there are neither errors or warnings reported but when the generated .rpm file should be installed with "rpm -ivh" the installation fails with:

**error: unpacking of archive failed** on file /redhat-release;5f2712a5: **cpio: Digest mismatch**
error: Example-0:1.0-.noarch: install failed

# Steps to reprodude:

Use this Dockerfile:

```
FROM oraclelinux:7

RUN yum -y install oracle-golang-release-el7
RUN yum -y install golang git ant file

RUN go get -u github.com/google/rpmpack/...

RUN echo "<project name='test' default='main' basedir='.'>" >/tmp/build.xml && \
    echo "  <target name='main'>" >>/tmp/build.xml && \
    echo "    <tar destfile='/tmp/generated-by-ant.tar'>" >>/tmp/build.xml  && \
    echo "      <tarfileset dir='/etc' username='root' group='root'>" >>/tmp/build.xml && \
    echo "        <include name='redhat-release'/>" >>/tmp/build.xml && \
    echo "      </tarfileset>" >>/tmp/build.xml && \
    echo "    </tar>" >>/tmp/build.xml && \
    echo "  </target>" >>/tmp/build.xml&& \
    echo "</project>" >> /tmp/build.xml

RUN ant -f /tmp/build.xml
 
ENTRYPOINT ["bash"]
```

Build and run:

```
docker build -t rpmtest .
docker run --rm -it rpmtest
```

Run these commands in the Docker Container:

```
# Run file to determine the file type:
file /tmp/generated-by-ant.tar
# List the contents of the tar file (or extract it, it will work)
tar -tvf /tmp/generated-by-ant.tar
# Run the tar2rpm tool to generate the rpm
/root/go/bin/tar2rpm -file /tmp/example.rpm -name "Example" -version "1.0" --build_time "$(date +%s)" /tmp/generated-by-ant.tar

#Try to install the rpm
rpm -ivh /tmp/example.rpm
```

The last command will produce this error:

```
[root@e5a144d2b99f /]# rpm -ivh /tmp/example.rpm
Preparing...                          ################################# [100%]
Updating / installing...
   1:Example-0:1.0-                   ################################# [100%]
error: unpacking of archive failed on file /redhat-release;5f2712a5: cpio: Digest mismatch
error: Example-0:1.0-.noarch: install failed
[root@e5a144d2b99f /]# 
```

### PR DESCRIPTION
**Pull request by jarondl**
We had bad logic to deduce symlinks. This caused us to think
files with modes such as 0100644 are symlinks. All this change
does is properly compare the bits.

Fixes #49

### CODE REVIEW

File: rpm_test.go [hunk 1]
```diff
@@ -31,3 +30,28 @@ func TestFileOwner(t *testing.T) {
 		t.Errorf("File owner shoud be %s but is %s", group, r.filegroups[0])
 	}
 }
+
+// https://github.com/google/rpmpack/issues/49
+func Test100644(t *testing.T) {
+	r, err := NewRPM(RPMMetaData{})
+	if err != nil {
+		t.Errorf("NewRPM returned error %v", err)
```
Comment (alexaguilera93) [inline rpm_test.go:38]: Maybe just  t.Fatalf("NewRPM returned error %v", err) here?

Comment (jarondl) [reply rpm_test.go:38]: Thank you, Done.
