### PR TITLE
Allowlist for directories

### LINKED ISSUE #62: Unable to install the built rpm (without force)
Ive been trying to build an rpm using `pkg_tar2rpm`

when i go to install the rpm im seeing the following errors

```console
Error: Transaction check error:
  file /opt from install of envoy-0:1.19.0-pre.noarch conflicts with file from package filesystem-3.8-2.el8.x86_64
  file /usr from install of envoy-0:1.19.0-pre.noarch conflicts with file from package filesystem-3.8-2.el8.x86_64
  file /usr/bin from install of envoy-0:1.19.0-pre.noarch conflicts with file from package filesystem-3.8-2.el8.x86_64
```

if i use `rpm -i --force my.rpm` it works - im wondering what im doing wrong (or not doing right) that is fooing the paths in the package

### PR DESCRIPTION
**Pull request by jarondl**
Users reported issues with installing rpms that have directories from the core filesystem (such as /etc/, /var/, etc). This change adds the option in `tar2rpm` and in the bazel rules, to only include certain directories. This talks about the directory itself, the content is always included.

Fixes #62

### CODE REVIEW

File: cmd/tar2rpm/main.go [hunk 1]
```diff
@@ -142,15 +146,32 @@ func main() {
 			Requires:    requires,
 			Conflicts:   conflicts,
 		})
+	if err != nil {
+		fmt.Fprintf(os.Stderr, "tar2rpm error: %v\n", err)
+		os.Exit(1)
+	}
+	if *useDirAllowlist {
+		al := map[string]bool{}
```
Comment (alexaguilera93) [inline cmd/tar2rpm/main.go:154]: I think declaring as
var al map[string]bool 

would be better, to avoid possibly unnecessary allocation.

File: tar.go [hunk 2]
```diff
@@ -57,13 +57,23 @@ func FromTar(inp io.Reader, md RPMMetaData) (*RPM, error) {
 		}
 		mtime := uint32(h.ModTime.Unix())
 
+    // Sometimes the tar has no uname and gname. RPM expects these to always exist.
+    owner := h.Uname
+    if owner == "" {
+      owner = "root"
```
Comment (alexaguilera93) [inline tar.go:63]: Could defaulting to root be an issue here if a user is unpacking as root?

**Review by alexaguilera93 — COMMENTED** [review]
LGTM - just a couple of small comments
